# Base image 
FROM python:2.7.12

MAINTAINER jeremy.pumphrey@nih.gov

ENV INSTALL_PATH /usr/app
RUN mkdir -p $INSTALL_PATH && chmod 777 $INSTALL_PATH
WORKDIR $INSTALL_PATH

#Install requirements
COPY requirements.txt .
RUN pip install -r requirements.txt

# Add the app code 
COPY . .

#Avoid running celery as root
USER nobody

# Default command 
CMD cd $INSTALL_PATH && ./docker-compose-env.sh && celery -A tasks.tasks worker --loglevel=INFO
