development:
  dynamo_endpoint: "http://localhost:8000"
  region: "us-east-1"
  port: "10241"

test:
  dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  region: "us-east-1"
  port: "10241"

uat:
  dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  region: "us-east-1"
  port: "10241"

production:
  dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  region: "us-east-1"
  port: "10241"
