development:
  dynamo_endpoint: "http://localhost:8000"
  patient_endpoint: "http://localhost:10240"
  rule_endpoint: "http://localhost:8080"
  patient_post_path: "/api/v1/patients/ir"
  rule_path: "/api/v1/rules/sample_control_report/"
  shipments_path: "/api/v1/patients/shipments/"
  bot_name: "pedmatchbot_dev"
  slack_channel_id: "C2N1BJX0U"
  region: "us-east-1"
  port: "10241"
  bucket: "pedmatch-dev"
  tmp_file_dir: "/tmp"
  polling_interval: 10
  read_capacity: 5
  write_capacity: 5
  aws_download_time_limit: 600

test:
  dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  patient_endpoint: "https://pedmatch-int.nci.nih.gov"
  patient_post_path: "/api/v1/patients/ir"
  rule_path: "/api/v1/rules/sample_control_report/"
  shipments_path: "/api/v1/patients/shipments/"
  bot_name: "pedmatchbot_test"
  slack_channel_id: "C2NDP4QKA"
  region: "us-east-1"
  port: "10241"
  bucket: "pedmatch-int"
  tmp_file_dir: "/tmp"
  polling_interval: 10
  read_capacity: 5
  write_capacity: 5
  ir_queue_name: "ion_reporter_queue"
  aws_download_time_limit: 600

uat:
  dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  patient_post_path: "/api/v1/patients/ir"
  patient_endpoint: "https://pedmatch-uat.nci.nih.gov"
  rule_path: "/api/v1/rules/sample_control_report/"
  shipments_path: "/api/v1/patients/shipments/"
  bot_name: "pedmatchbot_uat"
  slack_channel_id: "C2NE0QS57"
  region: "us-east-1"
  port: "10241"
  bucket: "pedmatch-uat"
  tmp_file_dir: "/tmp"
  polling_interval: 10
  read_capacity: 5
  write_capacity: 5
  ir_queue_name: "ion_reporter_queue"
  aws_download_time_limit: 600

production:
  dynamo_endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  patient_endpoint: "https://pedmatch.nci.nih.gov"
  patient_post_path: "/api/v1/patients/ir"
  rule_path: "/api/v1/rules/sample_control_report/"
  shipments_path: "/api/v1/patients/shipments/"
  bot_name: "pedmatchbot_prod"
  slack_channel_id: "C2NDQKS4E"
  region: "us-east-1"
  port: "10241"
  bucket: "pedmatch"
  tmp_file_dir: "/tmp"
  polling_interval: 10
  read_capacity: 10
  write_capacity: 10
  ir_queue_name: "ion_reporter_queue"
  aws_download_time_limit: 600
